CREATE TABLE Person
(
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);

 - Создаем таблицу book:
CREATE TABLE Book
(
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL,
    author varchar NOT NULL,
    year int check (year > 0) NOT NULL,
    user_id int REFERENCES Person (user_id) ON DELETE SET NULL
);

ALTER TABLE book ADD COLUMN created_at TIMESTAMP